### ISSUE TITLE
It seems incompatible with node 4.1.1

### ISSUE THREAD

**Issue by xcv58** [blue-systems-group/code.metalsmith-blue#1]
Caused by:
```javascript
require('harmonize')(['harmony-generators']);
```

Output:
```
/usr/local/Cellar/node/4.1.1/bin/node: bad option: --harmony-generators
```

**Comment by gchallen** [comment]
Fixed. package.json now requires node 0.12.7+. Note that the problems with node in version 0 are not particularly important to us as part of a build tool.
